Web/StayFit.Web/Controllers/DiariesController.cs
namespace StayFit.Web.Controllers
{
    using System;
    using System.Globalization;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using StayFit.Data.Models;
    using StayFit.Services.Data;
    using StayFit.Web.ViewModels.Diaries;
    using StayFit.Web.ViewModels.Users;

    public class DiariesController : Controller
    {
        private readonly IDiariesService diariesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUsersService usersService;

        public DiariesController(IDiariesService diariesService, UserManager<ApplicationUser> userManager, IUsersService usersService)
        {
            this.diariesService = diariesService;
            this.userManager = userManager;
            this.usersService = usersService;
        }

        [Authorize]
        public async Task<IActionResult> Add(int mealId, double quantity)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.diariesService.AddMealToDiaryAsync(mealId, user.Id, quantity);

            return this.Redirect(nameof(this.FoodDiary));
        }

        [Authorize]
        public async Task<IActionResult> FoodDiary(DateTime? date)
        {
            DateTime currentDate;

            if (date == null)
            {
                currentDate = DateTime.UtcNow.Date;
            }
            else
            {
                var inputDateToShortDateString = date.Value.Date.ToShortDateString();

                currentDate = DateTime.ParseExact(inputDateToShortDateString, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var viewModel = new FoodDiaryListViewModel
            {
                CurrentDate = currentDate,
                User = this.usersService.GetById<UserCaloriesGoalViewModel>(user.Id),
                Diary = this.diariesService.GetUserFoodDiary<FoodDiaryInListViewModel>(user.Id, currentDate),
                RecentMeals = this.diariesService.GetUserRecentMeals<FoodDiaryInListViewModel>(user.Id),
            };

            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.diariesService.DeleteMealFromDiaryAsync(id, user.Id);

            return this.RedirectToAction(nameof(this.FoodDiary));
        }

        public async Task<IActionResult> WorkoutDiary(DateTime? date)
        {
            DateTime currentDate;

            if (date == null)
            {
                currentDate = DateTime.UtcNow.Date;
            }
            else
            {
                var inputDateToShortDateString = date.Value.Date.ToShortDateString();

                currentDate = DateTime.ParseExact(inputDateToShortDateString, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var viewModel = new WorkoutDiaryListViewModel
            {
                Diary = this.diariesService.GetUserWorkoutDiary<WorkoutDiaryInListViewModel>(user.Id, currentDate),
                CurrentDate = currentDate,
            };

            return this.View(viewModel);
        }
    }
}

Web/StayFit.Web/Controllers/ExercisesController.cs
namespace StayFit.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using StayFit.Data.Models;
    using StayFit.Services.Data;
    using StayFit.Web.ViewModels.Exercises;
    using StayFit.Web.ViewModels.Scheduler;

    public class ExercisesController : BaseController
    {
        private readonly IExercisesService exercisesService;
        private readonly IWorkoutService workoutService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IEquipmentService equipmentService;

        public ExercisesController(IExercisesService exercisesService, IWorkoutService workoutService, UserManager<ApplicationUser> userManager, IEquipmentService equipmentService)
        {
            this.exercisesService = exercisesService;
            this.workoutService = workoutService;
            this.userManager = userManager;
            this.equipmentService = equipmentService;
        }

        public IActionResult Index()
        {
            var viewModel = new SearchExerciseInputModel();

            viewModel.Equipments = this.equipmentService.GetAllEquipments();

            return this.View(viewModel);
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 14;

            var viewModel = new ExercisesListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                TotalCount = this.exercisesService.GetCount(),
                Exercises = this.exercisesService.GetAll<ExerciseViewModel>(id, ItemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var viewModel = this.exercisesService.GetExerciseDetails<ExerciseDetailsViewModel>(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Workout()
        {
            var viewModel = new ExerciseInputModel
            {
                Exercises = this.exercisesService.GetAll<ExerciseDropdownViewModel>(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Workout([FromBody]List<ExerciseInputModel> inputModel)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.workoutService.CreateAsync(inputModel, user.Id);

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult Search(SearchExerciseInputModel inputModel, int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 15;

            var result = this.exercisesService.GetAllSearched<ExerciseViewModel>(inputModel, id);

            if (result.Count == 0)
            {
                return this.NotFound();
            }

            var viewModel = new ExercisesListViewModel
            {
                PageNumber = id,
                ItemsPerPage = ItemsPerPage,
                TotalCount = result.Count,
                Exercises = result.Exercises,
                Name = inputModel.Name,
                BodyPart = inputModel.BodyPart,
                Difficulty = inputModel.Difficulty,
                ExerciseType = inputModel.ExerciseType,
                EquipmentId = inputModel.EquipmentId,
            };

            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> Scheduler([FromRoute] int year, int month)
        {
            if (month < 1)
            {
                year--;
                month = 12;
            }
            else if (month > 12)
            {
                year++;
                month = 1;
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var events = new SchedulerViewModel
            {
                Events = this.workoutService.GetEvents(user.Id),
                Month = month,
                Year = year,
            };

            return this.View(events);
        }
    }
}

Web/StayFit.Web/Controllers/MealsController.cs
namespace StayFit.Web.Controllers
{
    using System;
    using System.Text;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using StayFit.Data.Models;
    using StayFit.Services.Data;
    using StayFit.Services.Messaging;
    using StayFit.Services.ViewRender;
    using StayFit.Web.ViewModels.Meals;
    using StayFit.Web.ViewModels.Users;

    public class MealsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ICategoriesService categoriesService;
        private readonly ISubCategoriesService subCategoriesService;
        private readonly IMealService mealService;
        private readonly IWebHostEnvironment environment;
        private readonly IEmailSender emailSender;
        private readonly IViewRenderService viewRenderService;
        private readonly IUsersService usersService;

        public MealsController(
            UserManager<ApplicationUser> userManager,
            ICategoriesService categoriesService,
            ISubCategoriesService subCategoriesService,
            IMealService mealService,
            IWebHostEnvironment environment,
            IEmailSender emailSender,
            IViewRenderService viewRenderService,
            IUsersService usersService)
        {
            this.userManager = userManager;
            this.categoriesService = categoriesService;
            this.subCategoriesService = subCategoriesService;
            this.mealService = mealService;
            this.environment = environment;
            this.emailSender = emailSender;
            this.viewRenderService = viewRenderService;
            this.usersService = usersService;
        }

        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new CreateMealViewModel();

            viewModel.CategoriesItems = this.categoriesService.GetAllCategories();

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateMealInputModel inputModel)
        {
            var viewModel = new CreateMealViewModel();

            if (!this.ModelState.IsValid)
            {
                viewModel.CategoriesItems = this.categoriesService.GetAllCategories();

                return this.View(viewModel);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.mealService.CreateAsync(inputModel, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception exception)
            {
                this.ModelState.AddModelError(string.Empty, exception.Message);

                viewModel.CategoriesItems = this.categoriesService.GetAllCategories();

                return this.View(viewModel);
            }

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult CategorySubCategories(int categoryId)
        {
            var subCategories = this.subCategoriesService.GetAllSubCategories(categoryId);

            return this.Json(subCategories);
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 15;
            var viewModel = new MealListViewModel
            {
                PageNumber = id,
                TotalCount = this.mealService.GetAllMealsCount(),
                Meals = this.mealService.GetAll<MealInListViewModel>(id),
                ItemsPerPage = ItemsPerPage,
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> MealDetails(int id)
        {
            var viewModel = this.mealService.GetMealDetails<MealDetailsViewModel>(id);

            if (this.User.Identity.IsAuthenticated)
            {
                var user = await this.userManager.GetUserAsync(this.User);

                viewModel.CurrentUser = this.usersService.GetById<MealDetailsUserViewModel>(user.Id);
            }

            return this.View(viewModel);
        }

        public IActionResult Index()
        {
            var viewModel = new SearchMealInputModel();

            viewModel.CategoriesItems = this.categoriesService.GetAllCategories();

            return this.View(viewModel);
        }

        public IActionResult Search(SearchMealInputModel inputModel, int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 15;

            var result = this.mealService.GetAllSearched<MealInListViewModel>(inputModel, id);

            if (result.Count == 0)
            {
                return this.NotFound();
            }

            var viewModel = new MealListViewModel
            {
                PageNumber = id,
                TotalCount = result.Count,
                Meals = result.Meals,
                ItemsPerPage = ItemsPerPage,
                Name = inputModel.Name,
                CategoryId = inputModel.CategoryId,
                SubCategory = inputModel.SubCategory,
                SkillLevel = inputModel.SkillLevel,
                PortionCount = inputModel.PortionCount,
                PreparationTime = inputModel.PreparationTime,
                CookingTime = inputModel.CookingTime,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SendToEmail(int id)
        {
            // var html = this.viewRenderService.RenderToStringAsync(nameof(this.MealDetails), new Meal());

            var user = await this.userManager.GetUserAsync(this.User);

            var meal = this.mealService.GetMealDetails<MealInListViewModel>(id);
            var html = new StringBuilder();
            html.AppendLine($"<h1>{meal.Name}</h1>");
            html.AppendLine($"<h3>{meal.CategoryName}</h3>");
            html.AppendLine($"<img src=\"{meal.ImageUrl}\" />");
            await this.emailSender.SendEmailAsync("trainsleepeatandstayfit@gmail.com", "StayFit", $"{user.Email}", meal.Name, html.ToString());
            return this.RedirectToAction(nameof(this.MealDetails), new { id });
        }
    }
}

Web/StayFit.Web/Views/Shared/_ExercisesSearchPaginPartial.cshtml
@model StayFit.Web.ViewModels.Exercises.ExercisesListViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) {<text>disabled</text>}">
            <a class="page-link"
               asp-action="Search"
               asp-route-id="@Model.PreviousPageNumber"
               asp-route-name="@Model.Name"
               asp-route-bodyPart="@Model.BodyPart"
               asp-route-difficulty="@Model.Difficulty"
               asp-route-exerciseType="@Model.ExerciseType"
               asp-route-equipmentId="@Model.EquipmentId">
                Previous
            </a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-action="Search"
                       asp-route-id="@i"
                       asp-route-name="@Model.Name"
                       asp-route-bodyPart="@Model.BodyPart"
                       asp-route-difficulty="@Model.Difficulty"
                       asp-route-exerciseType="@Model.ExerciseType"
                       asp-route-equipmentId="@Model.EquipmentId">
                        @i
                    </a>
                </li>
            }
        }
        <li class="page-item active">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-action="Search"
                       asp-route-id="@i"
                       asp-route-name="@Model.Name"
                       asp-route-bodyPart="@Model.BodyPart"
                       asp-route-difficulty="@Model.Difficulty"
                       asp-route-exerciseType="@Model.ExerciseType"
                       asp-route-equipmentId="@Model.EquipmentId">
                        @i
                    </a>
                </li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {<text>disabled</text>}">
            <a class="page-link"
               asp-action="Search"
               asp-route-id="@Model.NextPageNumber"
               asp-route-name="@Model.Name"
               asp-route-bodyPart="@Model.BodyPart"
               asp-route-difficulty="@Model.Difficulty"
               asp-route-exerciseType="@Model.ExerciseType"
               asp-route-equipmentId="@Model.EquipmentId">
                Next
            </a>
        </li>
    </ul>
</nav>

Web/StayFit.Web/Views/Shared/_Layout.cshtml
@using StayFit.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/scheduler.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/404error.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/500error.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light navbar-dark bg-primary border-bottom box-shadow mb-3" id="navbar_top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Meals" asp-action="Index">Meals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Exercises" asp-action="Index">Exercises</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Diaries" asp-action="FoodDiary">Food Diary</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Diaries" asp-action="WorkoutDiary">Workout Diary</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Exercises" asp-action="Scheduler" asp-route-year="@(DateTime.UtcNow.Year)" asp-route-month="@(DateTime.UtcNow.Month)">Scheduler</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/LoadSubCategories.js" asp-append-version="true"></script>
    <script src="~/js/AddIngredient.js" asp-append-version="true"></script>
    <script src="~/js/ProgressBar.js" asp-append-version="true"></script>
    <script src="~/js/PassMealId.js" asp-append-version="true"></script>
    <script src="~/js/ShowCommentForm.js" asp-append-version="true"></script>
    <script src="~/js/LikeComment.js" asp-append-version="true"></script>
    <script src="~/js/CreateWorkout.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/StayFit.Web/Views/Shared/_MealsSearchPaginPartial.cshtml
@model StayFit.Web.ViewModels.Meals.MealListViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) {<text>disabled</text>}">
            <a class="page-link"
               asp-action="Search"
               asp-route-id="@Model.PreviousPageNumber"
               asp-route-name="@Model.Name"
               asp-route-categoryId="@Model.CategoryId"
               asp-route-subCategory="@Model.SubCategory"
               asp-route-skillLevel="@Model.SkillLevel"
               asp-route-portionCount="@Model.PortionCount"
               asp-route-preparationTime="@Model.PreparationTime"
               asp-route-cookingTime="@Model.CookingTime">
                Previous
            </a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-action="Search"
                       asp-route-id="@i"
                       asp-route-name="@Model.Name"
                       asp-route-categoryId="@Model.CategoryId"
                       asp-route-subCategory="@Model.SubCategory"
                       asp-route-skillLevel="@Model.SkillLevel"
                       asp-route-portionCount="@Model.PortionCount"
                       asp-route-preparationTime="@Model.PreparationTime"
                       asp-route-cookingTime="@Model.CookingTime">
                        @i
                    </a>
                </li>
            }
        }
        <li class="page-item active">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-action="Search"
                       asp-route-id="@i"
                       asp-route-name="@Model.Name"
                       asp-route-categoryId="@Model.CategoryId"
                       asp-route-subCategory="@Model.SubCategory"
                       asp-route-skillLevel="@Model.SkillLevel"
                       asp-route-portionCount="@Model.PortionCount"
                       asp-route-preparationTime="@Model.PreparationTime"
                       asp-route-cookingTime="@Model.CookingTime">
                        @i
                    </a>
                </li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {<text>disabled</text>}">
            <a class="page-link"
               asp-action="Search"
               asp-route-id="@Model.NextPageNumber"
               asp-route-name="@Model.Name"
               asp-route-categoryId="@Model.CategoryId"
               asp-route-subCategory="@Model.SubCategory"
               asp-route-skillLevel="@Model.SkillLevel"
               asp-route-portionCount="@Model.PortionCount"
               asp-route-preparationTime="@Model.PreparationTime"
               asp-route-cookingTime="@Model.CookingTime">Next</a>
        </li>
    </ul>
</nav>

Web/StayFit.Web/Views/Shared/_ModalPartial.cshtml
<form asp-controller="Diaries" asp-action="Add" method="get">
    <div class="modal fade" id="modalQuantity" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add to Your Diary</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="mealId" id="mealId" value="" />
                </div>
                <div class="row-cols-2 form-group offset-1">
                    <label for="quantity">Select product quantity</label>
                    <input class="form-control" type="number" step="any" min="0.01" max="100" name="quantity" value="" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Add to Diary</button>
                </div>
            </div>
        </div>
    </div>
</form>

Web/StayFit.Web/Views/Shared/_PagingPartial.cshtml
@model StayFit.Web.ViewModels.Pages.PagingViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) {<text>disabled</text>}">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {<text>disabled</text>}">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>